version: '2'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: 'db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root